// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVs1olZx0nldYF_WzbLxJ3UziXHGfQK9E',
    appId: '1:639961073738:web:ba1ccac0dcbd40fdc17eb3',
    messagingSenderId: '639961073738',
    projectId: 'platdel-88265',
    authDomain: 'platdel-88265.firebaseapp.com',
    storageBucket: 'platdel-88265.appspot.com',
    measurementId: 'G-T2RH5ZWDXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVpuWNy1ngHY4KI3r65ISamAngb08hPR8',
    appId: '1:639961073738:android:cdc80cd40707c26cc17eb3',
    messagingSenderId: '639961073738',
    projectId: 'platdel-88265',
    storageBucket: 'platdel-88265.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSnMVf1HCn4b8skpha-mTJS3KRgDnCR8',
    appId: '1:639961073738:ios:fc4f5886c7be88bbc17eb3',
    messagingSenderId: '639961073738',
    projectId: 'platdel-88265',
    storageBucket: 'platdel-88265.appspot.com',
    iosClientId: '639961073738-q9eh8fm2ubqvt3fsgeuktnts5l203qjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.platDel',
  );
}
